### ISSUE TITLE
Received exception when setting searchguard.ssl.transport.enabled = false

### ISSUE THREAD

**Issue by ewolinetz** [floragunncom/search-guard-ssl-docs#2]
I'm not sure if this is a docs or code issue but received this exception:
```
IllegalStateException[searchguard.ssl.transport.enabled must be set to 'true'];
```

In my elasticsearch.yaml:
```
searchguard:
  ssl:
    transport:
      enabled: false
```

Installed using `/usr/share/elasticsearch/bin/plugin install -b com.floragunn/search-guard-ssl/2.3.3.13`
